### ISSUE TITLE
Visualizer does not render points

### ISSUE THREAD

**Issue by wangchj** [davidmoten/rtree#29] opened 2015-10-26 03:07 UTC
I am trying to write a program to visualize the data points read from a file. However, `rtree.visualize().save()` does not render the data points as shown in the README example.

**Comment by davidmoten** [comment] 2015-10-26 05:00
I'll have a look thanks

**Comment by davidmoten** [comment] 2015-10-26 05:50
I've just tried and seems to work. Does the tree have any data in it (remember the rtree is immutable, when you add data you have to then use the rtree returned by the add method)? Can you post your code?

**Comment by wangchj** [comment] 2015-10-26 15:14
Hi yes the points (data) are present and MBRs are drawn. Please see the code below.

```java
import com.github.davidmoten.rtree.RTree;
import com.github.davidmoten.rtree.geometry.Geometries.*;
import com.github.davidmoten.rtree.geometry.Geometry;
import com.github.davidmoten.rtree.geometry.Point;
import com.github.davidmoten.rtree.geometry.Rectangle;

import java.io.*;
import java.util.*;

public class Visual 
{
    final static int imgWidth = 1000;
    final static int imgHeight = 1000;
    
    public static void main(String[] args) throws FileNotFoundException
    {
        Scanner scanner = new Scanner(new File(args[0]));
        RTree<Integer, Point> rtree = RTree.create();
        RTree<Integer, Point> rstar = RTree.star().create();
        int n = scanner.nextInt();
        
        for(int i = 0; i < n; i++) {
            float x = (float)scanner.nextInt();
            float y = (float)scanner.nextInt();
            rtree = rtree.add(i, Point.create(x, y));
            rstar = rstar.add(i, Point.create(x, y));
        }
    
        rtree.visualize(imgWidth, imgHeight).save(args[0] + ".rt.png");
        rstar.visualize(imgWidth, imgHeight).save(args[0] + ".rs.png");
    }
}
```

**Comment by davidmoten** [comment] 2015-11-11 11:13
Hi, a runnable test would be nice. I haven't reproduced the problem yet.

**Comment by dsmoses** [comment] 2015-11-17 15:43
I've noticed the same issue. In Visualizer.drawRectangle, I noticed that this appears to be related to the call to:

g.drawRect(rnd(x1), rnd(y1), rnd(x2 - x1), rnd(y2 - y1));

since x1 and x2, as well as y1 and y2, in a Point are the exact same values, this call is effectively the same as:

g.drawRect(rnd(x1), rnd(y1), 0, 0);

BTW, I am adding Points to the RTree via Geometries.pointGeographic(lon, lat) items in the call to RTree.add(T value, S geometry), and not Rectangles which may ultimately be the cause of the issue. I crudely modified and tested the code to check if rnd(x2 - x1) > 0, and if false to return a 1, guaranteeing in a minimum width and height of 1x1. However, it would probably be better/cleaner to check if the node is a Point geometry versus a Rectangle and to return a List<S extends Geometry> instead of List<RectangleDepth> when retrieving the nodeDepths, so one could then pass the list into a drawNode(Graphics2D g, List<S extends Geometry> nodes) method. Then, inside that method, if the node is an instanceof Point call:

Point2D.Double point = new Point2D.Double(x, y);

instead of always calling g.drawRect() for every node/Geometry.

FYI, I am running on Windows under JDK 1.8.0_45, in case this is specific to certain implementations of java.awt.Graphics2D.

**Comment by davidmoten** [comment] 2015-12-12 18:56
Thanks @wangchj and @dsmoses. I'll fix this soon, excuse my tardiness!

**Comment by davidmoten** [comment] 2015-12-12 22:36
I've taken the simple route of ensuring every mbr drawnn has a minimum height and width of 1.

**Comment by davidmoten** [comment] 2015-12-12 22:44
Released 0.7.2 to Maven Central with fix for this

**Closed** 2015-12-12 22:44 UTC
Labels: bug

**Comment by wangchj** [comment] 2016-01-21 04:22
@davidmoten Thank you for the fix!

**Comment by davidmoten** [comment] 2016-01-21 08:04
You're welcome, sorry for the delay, and thanks for reporting it.
