### ISSUE TITLE
RTree search function not invoking callback function number of expected times

### ISSUE THREAD

**Issue by mghildiy** [davidmoten/rtree#105] opened 2020-10-08 08:12 UTC
I have raised this issue on SO too.
https://stackoverflow.com/questions/64258345/rtree-search-function-not-invoking-callback-function-number-of-expected-times

I observe that callback function I pass to search method is not invoked expected number of times.
I observe it when rectangles are not overlapping.

**Comment by davidmoten** [comment] 2020-10-08 08:22
I didn't quite understand what you are trying to do and what the problem was. Can you make a failing unit test please that demonstrates the problem. The test should be as succinct as possible focusing on the unexpected behaviour, not your use case. Thanks.

**Comment by mghildiy** [comment] 2020-10-08 08:46
```
Rectangle mbb1 = Geometries.rectangleGeographic(72.96089172363281,19.17504474158168,72.96230792999268,19.190122840904767);
Rectangle mbb2 = Geometries.rectangleGeographic(72.96083271503448,19.173942709431888,72.96088099479675,19.174720466220187);
RTree<String, Rectangle> tree = RTree.create();
Map<String, Rectangle> nameByBoundingBox = new HashMap();
tree = tree.add("bb1", mbb1);
tree = tree.add("bb2", mbb2);
nameByBoundingBox.put("bb1", mbb1);
nameByBoundingBox.put("bb2", mbb2);

Map<String, String> pairs = new HashMap<>();
for(Map.Entry<String, Rectangle> entry : nameByBoundingBox.entrySet()) {
    tree.search(entry.getValue(), new Func2<Rectangle, Rectangle, Boolean>() {
            public Boolean call(Rectangle g, Rectangle r) {
                   //  find those items which are within 5 metres
                   return 0.0 <= g.distance(r) && g.distance(r) <= 5.0;
                }
            })
            .forEach((Entry<String, Rectangle> rectangle) -> {
                // don't pair up with itself
                if(!rectangle.value().equals(entry.getKey())) {
                    pairs.put(entry.getKey(), rectangle.value());
                }
            });
            // remove this node from rtree so that its not paired up again
            tree = tree.delete(entry.getKey(), nameByBoundingBox.get(entry.getKey()));
}
```

So I am basically looking to pair up those rectangles which are within 5 metres distance. I expect that for every iteration of for loop, number of times 'call' is invoked is number of times items left in rtree. So if we start with 2 rectangles in rtree, for first entry 'call' is called 2 times. Then I remove that entry using 'delete' method. So now 1 item is left. So for second entry, 'call' is invoked 1 time. So total 3 times 'call' must be invoked. But I observe that 'call' is invoked only twice.

**Comment by davidmoten** [comment] 2020-10-08 08:58
Thanks but please isolate further. I want to see one call to search that doesn't give what you expect or a call to delete that doesn't give you what you expect.

**Comment by mghildiy** [comment] 2020-10-08 09:37
So I have structured code a bit. I wanted to modify a counter inside 'call' method which I could then apply assert on. But it seems its not possible. So what I have done is that I have put a print out statement inside 'call'. I expect "Inside call" to be printed 3 times, but you would see only 2 times.

```
class Test {
     public static void main(String[] args) {
        Rectangle mbb1 = Geometries.rectangleGeographic(72.96089172363281, 19.17504474158168, 72.96230792999268, 19.190122840904767);
        Rectangle mbb2 = Geometries.rectangleGeographic(72.96083271503448, 19.173942709431888, 72.96088099479675, 19.174720466220187);
        RTree<String, Rectangle> tree = RTree.create();
        Map<String, Rectangle> nameByBoundingBox = new HashMap();
        tree = tree.add("bb1", mbb1);
        tree = tree.add("bb2", mbb2);
        nameByBoundingBox.put("bb1", mbb1);
        nameByBoundingBox.put("bb2", mbb2);

        Map<String, String> pairs = new HashMap<>();
        for (Map.Entry<String, Rectangle> entry : nameByBoundingBox.entrySet()) {
            tree.search(entry.getValue(), new Func2<Rectangle, Rectangle, Boolean>() {
                public Boolean call(Rectangle g, Rectangle r) {
                    //  find those items which are within 5 metres
                    System.out.println("Inside call");
                    return 0.0 <= g.distance(r) && g.distance(r) <= 5.0;
                }
            })
                    .forEach((Entry<String, Rectangle> rectangle) -> {
                        // don't pair up with itself
                        if (!rectangle.value().equals(entry.getKey())) {
                            pairs.put(entry.getKey(), rectangle.value());
                        }
                    });
            // remove this node from rtree so that its not paired up again
            tree = tree.delete(entry.getKey(), nameByBoundingBox.get(entry.getKey()));
        }

        System.out.println("At end");
    }
}
```
Please let me know if you need more inputs or action on my side.

**Comment by davidmoten** [comment] 2020-10-08 10:01
Hi, I'm trying to avoid some diagnostic work here. If there is a problem with the library then *one* call to `tree.search` or `tree.delete` is doing the wrong thing. Can you step through this three times yourself to see when something unexpected happens and then isolate so you have one tree object that shows the problem. No loops, just add and delete stuff from a tree and show it ends up in an unexpected state.

**Comment by mghildiy** [comment] 2020-10-08 11:03
So I removed delete part and loop, and now my code is:

```
tree.search(nameByBoundingBox.get("bb1"), new Func2<Rectangle, Rectangle, Boolean>() {
            public Boolean call(Rectangle g, Rectangle r) {
                //  find those items which are within 5 metres
                System.out.println("Inside call");
                return 0.0 <= g.distance(r) && g.distance(r) <= 5000.0;
            }
        })
                .forEach((Entry<String, Rectangle> rectangle) -> {
                    // don't pair up with itself
                    if (!rectangle.value().equals("bb1")) {
                        pairs.put("bb1", rectangle.value());
                    }
                });
```

When I run this code, 'call' is still invoked only once, even though there are 2 rectangles in tree.
I also output tree image at start and end, and both are same, as below.

![image](https://user-images.githubusercontent.com/10056406/95450349-c8d99300-0983-11eb-839e-26aaf86b80e9.png)

I don't see any modification in tree.

**Comment by mghildiy** [comment] 2020-10-08 11:19
Another observation I made. With following code,

```
tree.search(nameByBoundingBox.get("bb1"), 5)
                .forEach((Entry<String, Rectangle> rectangle) -> {
                    // don't pair up with itself
                    System.out.println("Inside foreach");
                    if (!rectangle.value().equals("bb1")) {
                        pairs.put("bb1", rectangle.value());
                    }
                });
```

I see 'Inside foreach' printed twice, as expected. So only when I pass callback function to search method, code is not working as expected.

**Comment by davidmoten** [comment] 2020-10-08 21:54
Wait a second, you shouldn't expect the call to be made once for every item in the tree. If it always did then it would be a pretty useless index wouldn't it! The distance check might be made on a bounding box around two items. If it fails then the distance check will fail for the two items as well. If there is a problem here you need to show me via the results of the search not the number of times the distance check is called.

**Comment by davidmoten** [comment] 2022-12-02 08:18
Closing as non-issue.

**Closed by davidmoten** 2022-12-02 08:18 UTC
Labels: question
